name: 设计讨论
description: 讨论游戏机制、平衡性或叙事设计
labels: ["question"]
body:
  - type: dropdown
    id: topic
    attributes:
      label: 讨论主题
      options:
        - 三资源系统
        - 模仿牌机制
        - 权谋循环
        - 结局设计
        - 平衡性
        - 其他
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: 背景/问题
      placeholder: 描述你想讨论的背景或问题
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 你的想法/提案
      placeholder: 分享你的想法或提案（可选）
